call .\..\setdir.bat
set KEYTOOL_HOME=%JAVA_HOME%

REM Other parameters
set ROOTCA_POLICY=policy_anything
set SUBCA_POLICY=policy_anything
set OSSL_CONFIG=openssl.conf

REM RootCA
set ROOTCA_KEY_FILENAME=%ROOTCA_FILE_PREFIX%.key
set ROOTCA_CERT_PEM_FILENAME=%ROOTCA_FILE_PREFIX%.pem.cer
set ROOTCA_CERT_DER_FILENAME=%ROOTCA_FILE_PREFIX%.der
set ROOTCA_CERTSTORE_FILENAME=%ROOTCA_FILE_PREFIX%.jks

REM SubCA
set SUBCA_KEY_FILENAME=%SUBCA_FILE_PREFIX%.key
set SUBCA_CSR_FILENAME=%SUBCA_FILE_PREFIX%.csr
set SUBCA_CERT_PEM_FILENAME=%SUBCA_FILE_PREFIX%.pem.cer
set SUBCA_CERT_DER_FILENAME=%SUBCA_FILE_PREFIX%.der
set SUBCA_CERTSTORE_FILENAME=%SUBCA_FILE_PREFIX%.jks
set SUBCA_CERTPATHSTORE_FILENAME=%SUBCA_FILE_PREFIX%.path.jks

REM EndEntity
set END_KEYSTORE_FILENAME=%END_FILE_PREFIX%_private.jks
set END_PKCS12_FILENAME=%END_FILE_PREFIX%_private.pfx
set END_CSR_FILENAME=%END_FILE_PREFIX%.csr
set END_CERTSTORE_FILENAME=%END_FILE_PREFIX%_public.jks
set END_TRUSTSTORE_FILENAME=%END_FILE_PREFIX%_truststore.jks
set END_TMP_CERT_PEM_FILENAME=%END_FILE_PREFIX%.tmp.pem.cer
set END_LONG_CERT_PEM_FILENAME=%END_FILE_PREFIX%.long.pem.cer
set END_CERT_PEM_FILENAME=%END_FILE_PREFIX%.pem.cer
set END_CERT_DER_FILENAME=%END_FILE_PREFIX%.der
set END_PRIVATEKEY_PEM_FILENAME=%END_FILE_PREFIX%.pk.pem
set END_PRIVATEKEY_PEM_NOPASS_FILENAME=%END_FILE_PREFIX%.pk.nopass.pem

REM Directories
set KEYS_DIR=.\keys\
set STORE_DIR=.\store\
set OUTPUTDIR=.\%END_FILE_PREFIX%\

set ROOT_CRL_DIR=.\..\rootca\crl\
set ROOT_CERTS_DIR=.\..\rootca\certs\
set SUB_CRL_DIR=.\..\subca\crl\
set SUB_CERTS_DIR=.\..\subca\certs\
set END_OUTPUT_DIR=.\..\end\%END_FILE_PREFIX%\

REM Directories + Files
set ROOTCA_KEY_FILE=%KEYS_DIR%%ROOTCA_KEY_FILENAME%
set ROOTCA_KEY_PASSWORD_TXT=%KEYS_DIR%%ROOTCA_KEY_FILENAME%.pas
set ROOTCA_CERT_PEM_FILE=%ROOT_CERTS_DIR%%ROOTCA_CERT_PEM_FILENAME%
set ROOTCA_CERT_DER_FILE=%ROOT_CERTS_DIR%%ROOTCA_CERT_DER_FILENAME%
set ROOTCA_CERTSTORE=%STORE_DIR%%ROOTCA_CERTSTORE_FILENAME%
set ROOTCA_CERTSTORE_PASSWORD_TXT=%STORE_DIR%%ROOTCA_CERTSTORE_FILENAME%.pas
set ROOTCA_CERTSTORE_LIST_TXT=%STORE_DIR%%ROOTCA_CERTSTORE_FILENAME%.list.txt

set SUBCA_KEY_FILE=%KEYS_DIR%%SUBCA_KEY_FILENAME%
set SUBCA_KEY_PASSWORD_TXT=%KEYS_DIR%%SUBCA_FILE_PREFIX%.pas
set SUBCA_CSR_FILE=%ROOT_CRL_DIR%%SUBCA_CSR_FILENAME%
set SUBCA_CERT_PEM_FILE=%SUB_CERTS_DIR%%SUBCA_CERT_PEM_FILENAME%
set SUBCA_CERT_DER_FILE=%SUB_CERTS_DIR%%SUBCA_CERT_DER_FILENAME%
set SUBCA_CERTSTORE=%STORE_DIR%%SUBCA_CERTSTORE_FILENAME%
set SUBCA_CERTSTORE_PASSWORD_TXT=%STORE_DIR%%SUBCA_CERTSTORE_FILENAME%.pas
set SUBCA_CERTSTORE_LIST_TXT=%STORE_DIR%%SUBCA_CERTSTORE_FILENAME%.list.txt
set SUBCA_CERTPATHSTORE=%STORE_DIR%%SUBCA_CERTPATHSTORE_FILENAME%
set SUBCA_CERTPATHSTORE_PASSWORD_TXT=%STORE_DIR%%SUBCA_CERTPATHSTORE_FILENAME%.pas
set SUBCA_CERTPATHSTORE_LIST_TXT=%STORE_DIR%%SUBCA_CERTPATHSTORE_FILENAME%.list.txt

set END_KEYSTORE=%OUTPUTDIR%%END_KEYSTORE_FILENAME%
set END_KEYSTORE_LIST_TXT=%OUTPUTDIR%%END_KEYSTORE_FILENAME%.list.txt
set END_KEYSTORE_LIST_TXT_AFTER_CREATE=%OUTPUTDIR%%END_KEYSTORE_FILENAME%.create.list.txt
set END_KEYSTORE_LIST_TXT_AFTER_ADD_ROOTCA=%OUTPUTDIR%%END_KEYSTORE_FILENAME%.rootca.list.txt
set END_KEYSTORE_LIST_TXT_AFTER_ADD_SUBCA=%OUTPUTDIR%%END_KEYSTORE_FILENAME%.subca.list.txt
set END_KEY_PASSWORD_TXT=%OUTPUTDIR%%END_FILE_PREFIX%.key.pas
set END_KEYSTORE_PASSWORD_TXT=%OUTPUTDIR%%END_FILE_PREFIX%.store.pas
set END_PKCS12_PASSWORD_TXT=%OUTPUTDIR%%END_FILE_PREFIX%.store.pfx.pas
set END_PRIVATEKEY_ALIAS_TXT=%OUTPUTDIR%%END_FILE_PREFIX%.alias
set END_PKCS12=%OUTPUTDIR%%END_PKCS12_FILENAME%
set END_PKCS12_LIST_TXT=%OUTPUTDIR%%END_PKCS12_FILENAME%.list.txt
set END_CSR_FILE=%SUB_CRL_DIR%%END_CSR_FILENAME%
set END_TMP_CERT_PEM_FILE=%OUTPUTDIR%%END_TMP_CERT_PEM_FILENAME%
set END_LONG_CERT_PEM_FILE=%END_OUTPUT_DIR%%END_LONG_CERT_PEM_FILENAME%
set END_CERT_PEM_FILE=%OUTPUTDIR%%END_CERT_PEM_FILENAME%
set END_CERT_DER_FILE=%OUTPUTDIR%%END_CERT_DER_FILENAME%
set END_CERTSTORE=%OUTPUTDIR%%END_CERTSTORE_FILENAME%
set END_CERTSTORE_PASSWORD_TXT=%OUTPUTDIR%%END_CERTSTORE_FILENAME%.pas
set END_CERTSTORE_LIST_TXT=%OUTPUTDIR%%END_CERTSTORE_FILENAME%.list.txt
set END_TRUSTSTORE=%OUTPUTDIR%%END_TRUSTSTORE_FILENAME%
set END_TRUSTSTORE_PASSWORD_TXT=%OUTPUTDIR%%END_TRUSTSTORE_FILENAME%.pas
set END_TRUSTSTORE_LIST_TXT=%OUTPUTDIR%%END_TRUSTSTORE_FILENAME%.list.txt
set END_PRIVATEKEY_PEM_FILE=%OUTPUTDIR%%END_PRIVATEKEY_PEM_FILENAME%
set END_PRIVATEKEY_PEM_NOPASS_FILE=%OUTPUTDIR%%END_PRIVATEKEY_PEM_NOPASS_FILENAME%