using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PetriNetworkSimulator.Entities.Enums
{
    public enum NetworkProperty
    {
        NAME,
        UNID,
        POINT_X,
        POINT_Y,
        SIZE_WIDTH,
        SIZE_HEIGHT,
        ORIGO,
        ORIGO_X,
        ORIGO_Y,
        RADIUS,
        ANGLERAD,
        ANGLE,
        WEIGHT,
        DELETE,
        PRIORITY,
        CHANGEDIRECTION,
        TEXT,
        FILENAME,
        GENNUMBER,
        TOKENPREFIX,
        POSITIONPREFIX,
        TRANSITIONPREFIX,
        NOTEPREFIX,
        STATEPREFIX,
        EDGEWEIGHT,
        DEFAULTCOLOR,
        SELECTEDCOLOR,
        MARKCOLOR,
        SHADOWCOLOR,
        NOTEPENCOLOR,
        NOTEBORDERCOLOR,
        NOTEBRUSHCOLOR,
        HELPCOLOR,
        STATECOLOR,
        DEFAULTFONT,
        NOTEFONT,
        VISIBLENOTES,
        VISIBLETRANSITIONLABEL,
        VISIBLEPRIORITY,
        VISIBLECAPACITY,
        VISIBLEEDGEWEIGHT,
        VISIBLEPOSITIONLABEL,
        VISIBLEEDGELABEL,
        STRAIGHTEN,
        VISIBLEEDGEHELPLINE,
        CURVE_OFFSET_X,
        CURVE_OFFSET_Y,
        VISIBLEREADYTOFIRETRANSACTIONS,
        MARKASREADYTOFIRECOLOR,
        VISIBLECLOCK,
        CLOCKCOLOR,
        LABELOFFSET_X,
        LABELOFFSET_Y,
        COLOR,
        TRANSITIONTYPE,
        CAPACITYLIMIT,
        SHOWANNOTATION,
        DELAY,
        CLOCKRADIUS,
        CLOCKOFFSET_X,
        CLOCKOFFSET_Y,
        EDGETYPE,
        SAMEORIGOX,
        SAMEORIGOY,
        CERTIFICATESUBJECT,
        LASTMODIFICATIONDATE
    }
}
