//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace PetriNetworkSimulator.RecentFiles
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://files.petrinetwork.hu")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://files.petrinetwork.hu", IsNullable = false)]
    public partial class PetriNetworkFiles
    {

        private RecentFile[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RecentFile", Namespace = "http://recentfile.petrinetwork.hu")]
        public RecentFile[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://recentfile.petrinetwork.hu")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://recentfile.petrinetwork.hu", IsNullable = false)]
    public partial class RecentFile
    {

        private string networkNameField;

        private string fileNameField;

        private string descriptionField;

        /// <remarks/>
        public string NetworkName
        {
            get
            {
                return this.networkNameField;
            }
            set
            {
                this.networkNameField = value;
            }
        }

        /// <remarks/>
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
}
